Do some cleanup found by static analysis
CyclopsMC/IntegratedTunnels pull request #45
Opened 2017-08-13 16:09 UTC by josephcsible

Remove useless null check
Trying to return null from a method that's supposed to return an int will
itself cause an exception, so this check isn't actually preventing any
exception.

Rename template parameter to avoid hiding the one from the class

Remove unnecessary imports

Specify type parameter of superclasses

2017-08-14 06:33 UTC, rubensworks requested changes
Thanks, just one minor comment.

2017-08-14 06:33 UTC, rubensworks commented on src/main/java/org/cyclops/integratedtunnels/part/PartStateItem.java
> -        return getPositionedAddonsNetwork() != null ? getPositionedAddonsNetwork().getSlotLimit(slot) : null;
`getPositionedAddonsNetwork()` can in fact return `null`. The `null` return value should just be replaced with `0` I assume?

2017-08-14 11:26 UTC, josephcsible commented on src/main/java/org/cyclops/integratedtunnels/part/PartStateItem.java
> -        return getPositionedAddonsNetwork() != null ? getPositionedAddonsNetwork().getSlotLimit(slot) : null;
Zero is my best guess too. I changed it to that.

2017-08-18 14:27 UTC, merged

2017-08-18 14:28 UTC, rubensworks commented
Thanks!